// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  'header--inner': string;
  'header--logo': string;
  'header--menu': string;
}
export const cssExports: CssExports;
export default cssExports;
